import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { UAPRecord } from "../schema";
import { incidentYear, isBasemap, skepticCandidates, SKEPTIC_SOURCE } from "./data";

// The case-file drawer: an opened classified file on a dark instrument screen
// (DESIGN.md). Monospace header, amber status pill, neutral off-white summary,
// mono metadata grid. Every missing field renders a placeholder, never a crash.

interface DrawerProps {
  record: UAPRecord | null;
  onClose: () => void;
}

const DASH = "—";

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
] as const;

// Humanize the ISO incident date at its source precision: "1947-08-04" →
// "Aug 4, 1947"; "2008-07" → "Jul 2008"; "1948" stays "1948". Anything that
// doesn't parse falls back to the raw string — display-only, never a crash.
function formatDate(r: UAPRecord): string {
  const d = r.incidentDate;
  if (!d) return incidentYear(r) !== null ? String(incidentYear(r)) : "undated";
  const [y, m, day] = d.split("-");
  const month = m !== undefined ? MONTHS[Number(m) - 1] : undefined;
  if (!month) return y ?? d;
  return day !== undefined ? `${month} ${Number(day)}, ${y}` : `${month} ${y}`;
}

function formatCoords(r: UAPRecord): string {
  if (r.lat === null || r.lon === null) return DASH;
  // Golden rule 7: round everything that reaches the UI.
  return `${r.lat.toFixed(2)}, ${r.lon.toFixed(2)}`;
}

function isHttpUrl(u: string): boolean {
  return u.startsWith("https://") || u.startsWith("http://");
}

// The document scan / rendering preview. Assets are generated by `pnpm media` into
// public/media/<id>.jpg (the id is the source-file content hash); a missing asset
// falls back to the placeholder block — fail soft, never a broken image.
// Clicking the scan opens it full-size in a lightbox (Esc or click closes).
function DocScan({ record }: { record: UAPRecord }) {
  const [failed, setFailed] = useState(false);
  const [enlarged, setEnlarged] = useState(false);
  const lightboxRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const label = record.media.rendering !== undefined ? "digital rendering" : "document scan";

  useEffect(() => {
    if (!enlarged) return;
    // Focus follows the dialog in, and returns to the enlarge button on close.
    const trigger = triggerRef.current;
    lightboxRef.current?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setEnlarged(false);
    };
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("keydown", onKey);
      trigger?.focus();
    };
  }, [enlarged]);

  if (record.media.docImage === undefined && record.media.rendering === undefined) return null;

  if (failed) {
    return (
      <div className="doc-scan-placeholder">
        <span className="mono-label">{label} · asset not available</span>
      </div>
    );
  }
  const src = `${import.meta.env.BASE_URL}media/${record.id}.jpg`;
  return (
    <>
      <figure className="doc-scan">
        <button
          ref={triggerRef}
          type="button"
          className="doc-scan-btn"
          onClick={() => setEnlarged(true)}
          aria-label={`Enlarge ${label}`}
        >
          <img
            src={src}
            alt={`${label} for case ${record.id}`}
            loading="lazy"
            onError={() => setFailed(true)}
          />
        </button>
        <figcaption className="mono-label">{label} · click to enlarge</figcaption>
      </figure>
      {/* Portaled to <body>: the drawer's backdrop-filter makes it the
          containing block for fixed descendants — inside it, the "full-screen"
          lightbox would be clipped to the panel. */}
      {enlarged &&
        createPortal(
          <div
            ref={lightboxRef}
            className="scan-lightbox"
            role="dialog"
            aria-modal="true"
            aria-label={`Enlarged ${label}`}
            tabIndex={-1}
            onClick={() => setEnlarged(false)}
          >
            <img src={src} alt={`${label} for case ${record.id}, enlarged`} />
          </div>,
          document.body,
        )}
    </>
  );
}

// Skeptic layer: orbital launches near the incident date, as neutral context.
// Three honest states: not checkable (no day-precision date), checked-and-empty,
// and a candidate list. Nothing here asserts an explanation.
const SKEPTIC_SHOWN = 5;

function SkepticSection({ record }: { record: UAPRecord }) {
  const candidates = skepticCandidates(record.id);
  return (
    <section className="skeptic">
      <span className="mono-label">prosaic context</span>
      {candidates === undefined ? (
        <p className="skeptic-empty">
          not cross-referenced — the incident date lacks day precision
        </p>
      ) : candidates.length === 0 ? (
        <p className="skeptic-empty">no orbital launches within ±1 day of the incident</p>
      ) : (
        <>
          <ul className="skeptic-list">
            {candidates.slice(0, SKEPTIC_SHOWN).map((c, i) => (
              <li key={`${c.date}-${i}`} className="skeptic-row">
                <span className="skeptic-date">{c.date}</span>
                <span className="skeptic-what">
                  {c.vehicle} · {c.payload}
                  {c.site ? ` · ${c.site}` : ""}
                </span>
              </li>
            ))}
          </ul>
          {candidates.length > SKEPTIC_SHOWN && (
            <p className="skeptic-empty">+{candidates.length - SKEPTIC_SHOWN} more in window</p>
          )}
        </>
      )}
      <p className="skeptic-note">
        {SKEPTIC_SOURCE || "orbital launches near the incident date"}. Context only — no
        explanation is asserted.
      </p>
    </section>
  );
}

// The minimal card for a Blue Book basemap dot: these are catalog entries
// (date, location, precision, source), not released documents — the card shows
// exactly that much and says so, rather than dressing them up as case files.
function BluebookCard({ record: r, onClose }: { record: UAPRecord; onClose: () => void }) {
  return (
    <aside className="drawer" aria-label="Blue Book catalog entry">
      <header className="drawer-header">
        <div className="drawer-title">
          <span className="mono-label">{r.sourceAgency} · project blue book</span>
          <span className="drawer-case-id">unknown #{r.id}</span>
        </div>
        <div className="drawer-header-actions">
          <button type="button" className="drawer-close" onClick={onClose} aria-label="Close catalog entry">
            ✕
          </button>
        </div>
      </header>

      <dl className="meta-grid drawer-meta-solo">
        <dt>incident date</dt>
        <dd>{formatDate(r)}</dd>
        <dt>location</dt>
        <dd>{r.locationRaw || DASH}</dd>
        <dt>coordinates</dt>
        <dd>{formatCoords(r)}</dd>
        <dt>geo precision</dt>
        <dd className="meta-signal">{r.geoPrecision}</dd>
        <dt>source</dt>
        <dd>
          {isHttpUrl(r.sourceUrl) ? (
            <a className="meta-signal" href={r.sourceUrl} target="_blank" rel="noreferrer">
              unknowns catalog ↗
            </a>
          ) : (
            DASH
          )}
        </dd>
      </dl>

      <p className="drawer-note">
        A USAF Project Blue Book case (1947–1969) the Air Force closed as &quot;unidentified.&quot;
        It is part of the historical basemap: the catalog records only the date and place — no
        released document accompanies it in the PURSUE archive.
      </p>
    </aside>
  );
}

export function Drawer({ record, onClose }: DrawerProps) {
  if (!record) return null;
  if (isBasemap(record)) return <BluebookCard record={record} onClose={onClose} />;
  const r = record;

  return (
    <aside className="drawer" aria-label="Case file">
      <header className="drawer-header">
        <div className="drawer-title">
          <span className="mono-label">
            {r.sourceAgency} · {r.docType}
          </span>
          <span className="drawer-case-id">#{r.id}</span>
        </div>
        <div className="drawer-header-actions">
          {!r.resolved && <span className="status-pill">unresolved</span>}
          <button type="button" className="drawer-close" onClick={onClose} aria-label="Close case file">
            ✕
          </button>
        </div>
      </header>

      <DocScan key={r.id} record={r} />

      <p className="drawer-summary">{r.summary || "No summary available for this record."}</p>

      {/* where & when lead the file (Phase 5 weighting) — the administrative
          fields answer follow-up questions and read quieter */}
      <dl className="meta-grid">
        <dt>incident date</dt>
        <dd className="meta-primary">{formatDate(r)}</dd>
        <dt>location</dt>
        <dd className="meta-primary">{r.locationRaw || DASH}</dd>
        <dt>coordinates</dt>
        <dd className="meta-quiet">{formatCoords(r)}</dd>
        <dt>geo precision</dt>
        <dd className="meta-signal">{r.geoPrecision}</dd>
        <dt>object class</dt>
        <dd>{r.objectClass}</dd>
        <dt>redaction</dt>
        <dd className="meta-alert">
          {r.redactionPct === null ? DASH : `${Math.round(r.redactionPct)}%`}
        </dd>
        <dt>release</dt>
        <dd className="meta-quiet">{r.release || DASH}</dd>
        <dt>source</dt>
        <dd>
          {isHttpUrl(r.sourceUrl) ? (
            <a className="meta-signal" href={r.sourceUrl} target="_blank" rel="noreferrer">
              government record ↗
            </a>
          ) : (
            DASH
          )}
        </dd>
      </dl>

      <SkepticSection record={r} />
    </aside>
  );
}
