import { useState } from "react";
import type { UAPRecord } from "../schema";
import { incidentYear } from "./data";

// The case-file drawer: an opened classified file on a dark instrument screen
// (DESIGN.md). Monospace header, amber status pill, neutral off-white summary,
// mono metadata grid. Every missing field renders a placeholder, never a crash.

interface DrawerProps {
  record: UAPRecord | null;
  onClose: () => void;
}

const DASH = "—";

function formatDate(r: UAPRecord): string {
  if (r.incidentDate) return r.incidentDate;
  return incidentYear(r) !== null ? String(incidentYear(r)) : "undated";
}

function formatCoords(r: UAPRecord): string {
  if (r.lat === null || r.lon === null) return DASH;
  // Golden rule 7: round everything that reaches the UI.
  return `${r.lat.toFixed(2)}, ${r.lon.toFixed(2)}`;
}

function isHttpUrl(u: string): boolean {
  return u.startsWith("https://") || u.startsWith("http://");
}

// The document scan / rendering preview. Assets are generated by `pnpm media` into
// public/media/<id>.jpg (the id is the source-file content hash); a missing asset
// falls back to the placeholder block — fail soft, never a broken image.
function DocScan({ record }: { record: UAPRecord }) {
  const [failed, setFailed] = useState(false);
  const label = record.media.rendering !== undefined ? "digital rendering" : "document scan";
  if (record.media.docImage === undefined && record.media.rendering === undefined) return null;

  if (failed) {
    return (
      <div className="doc-scan-placeholder">
        <span className="mono-label">{label} · asset not available</span>
      </div>
    );
  }
  return (
    <figure className="doc-scan">
      <img
        src={`${import.meta.env.BASE_URL}media/${record.id}.jpg`}
        alt={`${label} for case ${record.id}`}
        loading="lazy"
        onError={() => setFailed(true)}
      />
      <figcaption className="mono-label">{label}</figcaption>
    </figure>
  );
}

export function Drawer({ record, onClose }: DrawerProps) {
  if (!record) return null;
  const r = record;

  return (
    <aside className="drawer" aria-label="Case file">
      <header className="drawer-header">
        <div className="drawer-title">
          <span className="mono-label">
            {r.sourceAgency} · {r.docType}
          </span>
          <span className="drawer-case-id">#{r.id}</span>
        </div>
        <div className="drawer-header-actions">
          {!r.resolved && <span className="status-pill">unresolved</span>}
          <button type="button" className="drawer-close" onClick={onClose} aria-label="Close case file">
            ✕
          </button>
        </div>
      </header>

      <DocScan key={r.id} record={r} />

      <p className="drawer-summary">{r.summary || "No summary available for this record."}</p>

      <dl className="meta-grid">
        <dt>incident date</dt>
        <dd>{formatDate(r)}</dd>
        <dt>location</dt>
        <dd>{r.locationRaw || DASH}</dd>
        <dt>coordinates</dt>
        <dd>{formatCoords(r)}</dd>
        <dt>geo precision</dt>
        <dd className="meta-signal">{r.geoPrecision}</dd>
        <dt>object class</dt>
        <dd>{r.objectClass}</dd>
        <dt>redaction</dt>
        <dd className="meta-alert">
          {r.redactionPct === null ? DASH : `${Math.round(r.redactionPct)}%`}
        </dd>
        <dt>release</dt>
        <dd>{r.release || DASH}</dd>
        <dt>source</dt>
        <dd>
          {isHttpUrl(r.sourceUrl) ? (
            <a className="meta-signal" href={r.sourceUrl} target="_blank" rel="noreferrer">
              government record ↗
            </a>
          ) : (
            DASH
          )}
        </dd>
      </dl>
    </aside>
  );
}
